import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from supabase import create_client

# 0. Validate required environment variables (fail loudly if a GitHub secret is misnamed/missing)
_required_env = ["SUPABASE_URL", "SUPABASE_KEY", "GMAIL_USER", "GMAIL_APP_PASSWORD"]
_missing_env = [name for name in _required_env if not os.environ.get(name)]
if _missing_env:
    raise SystemExit(
        "Missing required environment variables: " + ", ".join(_missing_env) + ". "
        "Check the GitHub repo secrets and the workflow env mapping "
        "(SUPABASE_URL<-SUPA_URL, SUPABASE_KEY<-SUPA_KEY, GMAIL_USER, GMAIL_APP_PASSWORD)."
    )

# 1. Connect to Supabase using Environment Variables
supabase_url = os.environ.get("SUPABASE_URL")
supabase_key = os.environ.get("SUPABASE_KEY")
supabase = create_client(supabase_url, supabase_key)

# 2. Fetch Vault Data
inv_resp = supabase.table('inventory').select('*').execute()
pkg_resp = supabase.table('packaging').select('*').execute()

inventory = inv_resp.data if inv_resp.data else []
packaging = pkg_resp.data if pkg_resp.data else []

# 3. Identify Low Stock (RM < 0.05kg, Packaging < 10 units)
low_rm = [item for item in inventory if item['quantity_kg'] < 0.05]
low_pkg = [item for item in packaging if item['remaining_quantity'] < 10]

# If everything is fully stocked, the script finishes silently.
if not low_rm and not low_pkg:
    print("Stock levels are healthy. No email required.")
    exit()

# 4. Construct the Email HTML
html_content = """
<html>
  <body style="font-family: Arial, sans-serif; color: #333;">
    <h2 style="color: #0F172A;">⚠️ Therapeutic Oils: Low Stock Alert</h2>
    <p>The following items have dropped below your minimum required thresholds in the lab vault:</p>
"""

if low_rm:
    html_content += "<h3 style='color: #B91C1C; border-bottom: 1px solid #ccc; padding-bottom: 5px;'>🧪 Raw Materials (< 50g)</h3><ul>"
    for rm in low_rm:
        current_g = rm['quantity_kg'] * 1000
        html_content += f"<li><b>{rm['trade_name']}</b> ({rm['rm_code']}): Only <b>{current_g:.1f}g</b> remaining</li>"
    html_content += "</ul>"

if low_pkg:
    html_content += "<h3 style='color: #B91C1C; border-bottom: 1px solid #ccc; padding-bottom: 5px;'>📦 Packaging Materials (< 10 units)</h3><ul>"
    for pkg in low_pkg:
        html_content += f"<li><b>{pkg['material_name']}</b> ({pkg['pm_code']}): Only <b>{pkg['remaining_quantity']} units</b> remaining</li>"
    html_content += "</ul>"

html_content += """
    <br><br>
    <p style="font-size: 12px; color: #777;"><i>This is an automated system alert generated by the Therapeutic Oils Lab Portal.</i></p>
  </body>
</html>
"""

# 5. Configure Email Credentials
sender_email = os.environ.get("GMAIL_USER")  # e.g., to.laboratories@gmail.com
sender_password = os.environ.get("GMAIL_APP_PASSWORD")
receiver_email = "to.laboratories@gmail.com"

# 6. Build and Send the Email Message
msg = MIMEMultipart("alternative")
msg["Subject"] = "⚠️ Lab Portal: Low Stock Alert"
msg["From"] = sender_email
msg["To"] = receiver_email
msg.attach(MIMEText(html_content, "html"))

try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
    print("Successfully sent low stock alert email.")
except Exception as e:
    print(f"Error sending email: {e}")
