import os
import json
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from supabase import create_client

# 0. Validate required environment variables (fail loudly if a GitHub secret is misnamed/missing)
_required_env = ["SUPABASE_URL", "SUPABASE_KEY", "GMAIL_USER", "GMAIL_APP_PASSWORD"]
_missing_env = [name for name in _required_env if not os.environ.get(name)]
if _missing_env:
    raise SystemExit(
        "Missing required environment variables: " + ", ".join(_missing_env) + ". "
        "Check the GitHub repo secrets and the workflow env mapping "
        "(SUPABASE_URL<-SUPA_URL, SUPABASE_KEY<-SUPA_KEY, GMAIL_USER, GMAIL_APP_PASSWORD)."
    )

# 1. Connect to Supabase using Environment Variables
supabase_url = os.environ.get("SUPABASE_URL")
supabase_key = os.environ.get("SUPABASE_KEY")
supabase = create_client(supabase_url, supabase_key)

# 2. Tables to back up
TABLES = [
    'inventory', 'packaging', 'formulas', 'cogs_records',
    'finished_products', 'sales_records', 'production_records',
    'consignment_records', 'clients', 'portfolios'
]

# 3. Fetch all data
backup_data = {
    "_meta": {
        "export_date": datetime.now().isoformat(),
        "version": "1.0",
        "table_count": 0,
        "record_count": 0
    }
}
total_records = 0
errors = []

for table in TABLES:
    try:
        resp = supabase.table(table).select('*').execute()
        rows = resp.data if resp.data else []
        backup_data[table] = rows
        total_records += len(rows)
        print(f"Exported {table}: {len(rows)} records")
    except Exception as e:
        backup_data[table] = []
        errors.append(f"{table}: {e}")
        print(f"Error exporting {table}: {e}")

backup_data["_meta"]["table_count"] = len([k for k in backup_data if not k.startswith("_")])
backup_data["_meta"]["record_count"] = total_records

# 4. Save to file
filename = f"therapeutic_oils_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
with open(filename, 'w') as f:
    json.dump(backup_data, f, indent=2, default=str)

# 5. Build summary HTML
summary_rows = ""
for k, v in backup_data.items():
    if not k.startswith("_") and isinstance(v, list):
        summary_rows += f"<tr><td style='padding: 6px 12px; border-bottom: 1px solid #eee;'>{k}</td><td style='padding: 6px 12px; border-bottom: 1px solid #eee; text-align: right;'><b>{len(v)}</b></td></tr>"

errors_html = ""
if errors:
    errors_html = "<div style='background: #FEF2F2; padding: 12px; margin-top: 16px; border-radius: 6px;'><b>⚠️ Some tables had errors:</b><ul>"
    for err in errors:
        errors_html += f"<li>{err}</li>"
    errors_html += "</ul></div>"

html_content = f"""
<html>
  <body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto;">
    <h2 style="color: #0F172A;">📦 Therapeutic Oils: Weekly Backup</h2>
    <p>Your weekly database snapshot is attached. Save this file in a safe location.</p>

    <div style="background: #F0F9FF; padding: 16px; border-radius: 8px; margin: 16px 0;">
      <p style="margin: 4px 0;"><b>Export Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
      <p style="margin: 4px 0;"><b>Total Tables:</b> {backup_data['_meta']['table_count']}</p>
      <p style="margin: 4px 0;"><b>Total Records:</b> {total_records}</p>
    </div>

    <h3 style="color: #0F172A; border-bottom: 1px solid #ccc; padding-bottom: 5px;">📊 Records per Table</h3>
    <table style="width: 100%; border-collapse: collapse; margin-top: 12px;">
      <thead>
        <tr style="background: #F1F5F9;">
          <th style="padding: 8px 12px; text-align: left;">Table</th>
          <th style="padding: 8px 12px; text-align: right;">Record Count</th>
        </tr>
      </thead>
      <tbody>
        {summary_rows}
      </tbody>
    </table>

    {errors_html}

    <br><br>
    <p style="font-size: 12px; color: #777;"><i>This is an automated weekly backup generated by the Therapeutic Oils Lab Portal. To restore from this backup, log into the ERP and use Admin Tools → Backup & Restore.</i></p>
  </body>
</html>
"""

# 6. Email credentials
sender_email = os.environ.get("GMAIL_USER")
sender_password = os.environ.get("GMAIL_APP_PASSWORD")
receiver_email = "to.laboratories@gmail.com"

# 7. Build email with attachment
msg = MIMEMultipart()
msg["Subject"] = f"📦 Lab Portal: Weekly Backup ({datetime.now().strftime('%Y-%m-%d')})"
msg["From"] = sender_email
msg["To"] = receiver_email
msg.attach(MIMEText(html_content, "html"))

# Attach backup JSON
with open(filename, 'rb') as f:
    part = MIMEBase('application', 'json')
    part.set_payload(f.read())
encoders.encode_base64(part)
part.add_header('Content-Disposition', f'attachment; filename={filename}')
msg.attach(part)

# 8. Send
try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
    print(f"Successfully sent weekly backup email with {filename} attached.")
except Exception as e:
    print(f"Error sending email: {e}")
